---
title: "stl_lead_inequity"
author: "Alex Vand"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";") %>% 
  clean_names() %>% 
  mutate(prop_white = (white / total_pop) * 100) %>% 
  mutate(pct_elevated = str_replace(pct_elevated,
                                    pattern = ",",
                                    replacement = ".")) %>% 
  mutate(pct_elevated = as.numeric(pct_elevated))
```

```{r}
names(stl_lead)
summary(stl_lead)
dim(stl_lead)
skim(stl_lead)
```

## Create a scatterplot

```{r fig.width = 5, fig.height = 5}
stl_lead_plot <- ggplot(data = stl_lead, aes(x = prop_white, y = pct_elevated)) +
  geom_point(color = "purple",
             alpha = 0.5,
             size = 1,
             shape = "triangle")

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), plot = stl_lead_plot, width = 6, height = 5)
```

## Create a histogram

```{r}
stl_lead_histogram <- ggplot(data = stl_lead, aes(x = pct_elevated)) +
  geom_histogram(color = "red",
                 fill = "blue",
                 size = 2)

stl_lead_histogram

ggsave(here::here("figs", "stl_lead_histogram.jpg"), plot = stl_lead_histogram)
```



